In [5]:
#rnn练习
import torch

#初始化参数
batch_size=1
seq_len=3
input_size=4
hidden_size=2

#创建数据集
dataset=torch.randn(seq_len,batch_size,input_size)
print(dataset)
#隐藏层初始化
hidden=torch.zeros(batch_size,hidden_size)

tensor([[[ 0.6860,  0.0308,  0.5203,  2.2268]],

        [[ 0.3569, -1.3209,  1.4775,  0.8330]],

        [[-0.1742,  0.2578, -0.8669,  0.5733]]])


In [6]:
#模型构建
cell=torch.nn.RNNCell(input_size=input_size,hidden_size=hidden_size)

In [7]:
#训练模型
for idx,input in enumerate(dataset):
    print('='*20,idx,'='*20)
    print('input_size:',input.shape)

    hidden=cell(input,hidden)

    print('output_size:',hidden.shape)
    print(hidden)

==================== 0 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[0.3388, 0.2763]], grad_fn=<TanhBackward0>)
==================== 1 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[ 0.6642, -0.5018]], grad_fn=<TanhBackward0>)
==================== 2 ====================
input_size: torch.Size([1, 4])
output_size: torch.Size([1, 2])
tensor([[-0.1469, -0.5633]], grad_fn=<TanhBackward0>)
