In [5]:
#数据处理练习
import torch

In [6]:
x=torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
#矩阵重塑
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
#广播机制
#对于同维度不同行列矩阵，进行扩充为最大数，如3,2并进行对应相加
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
