In [12]:
#数据处理练习
import torch

In [13]:
x=torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [14]:
#矩阵重塑
X=x.reshape(3,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [15]:
#广播机制
#对于同维度不同行列矩阵，进行扩充为最大数，如3,2并进行对应相加
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [16]:
x=torch.tensor([3.0])
y=torch.tensor([4.0])

print(x+y,x-y,x*y,x/y)

tensor([7.]) tensor([-1.]) tensor([12.]) tensor([0.7500])


In [17]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
print(A,A+B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [25]:

Z=torch.ones((2,4,5))
print(Z.shape)

print(Z.sum(axis=1,keepdims=True).shape)
Z

torch.Size([2, 4, 5])
torch.Size([2, 1, 5])


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])