In [1]:
#泰坦尼克号练习
import torch
import numpy as np
import pandas as pd

In [2]:
#加载数据
file_path='Titanic_dataset/train.csv'

# 使用 pandas 读取数据
df = pd.read_csv(file_path)
#xy=np.genfromtxt(file_path,delimiter=',',skip_header=1,dtype=np.float32,encoding='utf-8')
selected_columns=df[['Pclass','Age', 'SibSp', 'Parch']].to_numpy()
x_data = torch.from_numpy(selected_columns)
print(selected_columns)
# print(x_data)

[[ 3. 22.  1.  0.]
 [ 1. 38.  1.  0.]
 [ 3. 26.  0.  0.]
 ...
 [ 3. nan  1.  2.]
 [ 1. 26.  0.  0.]
 [ 3. 32.  0.  0.]]
