# one-hot 实践


In [1]:
import numpy as np

# 语料库
corpus = [
    "这 是 第一个 文档",
    "这 是 第二个 文档",
    "这 是 最后 一个 文档",
    "现在 没有 文档了",
]

In [2]:
# 分词
words = []

for corpu in corpus:
    words.extend(corpu.split())
# 去重
words = list(set(words))
# 建立词典
words_dct = {word: index for index, word in enumerate(words)}
# 字典长度
vocab_size = len(words_dct)

## 1.手动实现


In [3]:
def get_one_hot(index):
    one_hot = [0 for _ in range(vocab_size)]
    one_hot[index] = 1
    return np.array(one_hot)

In [4]:
indexs = [words_dct[word] for word in corpus[0].split()]

one_hot_np = np.array([get_one_hot(index) for index in indexs])

one_hot_np

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## 2.sklearn 实现


In [5]:
from sklearn.preprocessing import LabelBinarizer

# 初始化编码器
lb = LabelBinarizer()
lb.fit(words)

lb.classes_

array(['一个', '文档', '文档了', '是', '最后', '没有', '现在', '第一个', '第二个', '这'],
      dtype='<U3')

In [6]:
sentence = corpus[0].split()
# 词转换
sk_one_hot = lb.transform(sentence)
print(sk_one_hot)

# 反向转换
sk_iv = lb.inverse_transform(sk_one_hot)
print(sk_iv)

[[0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]]
['这' '是' '第一个' '文档']
